on: pull_request
name: Apply_Test_1
jobs:
  merged-prs-filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: merged-prs-filter
      uses: actions/bin/filter@master
      with:
        args: merged true
    - name: base-branch-filter
      uses: hashicorp/terraform-github-actions/base-branch-filter@v0.4.0
      with:
        args: ^master$
    - name: terraform-init-apply
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: .
    - name: terraform-apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: .
        TF_ACTION_WORKSPACE: default
