version: 1
jobs:
  terraform:
    working_directory: ~/github-action/
    docker:
      - image: hashicorp/terraform:0.12.7
    steps:
      - checkout
      - run:
          name: "terraform fmt"
          command: |
            terraform fmt -diff=true -check=true
workflows:
  version: 1
  terraform:
    jobs:
      - terraform

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
